apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: sysdig-vuln-mgmt
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - web:
        url: https://github.com/sysdigdan/argocd-sysdig/releases/download/v0.0.37/extension.tar