apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: hello-world
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - git:
        url: https://github.com/sysdigdan/argocd-sysdig.git
    - web:
        url: https://github.com/sysdigdan/argocd-sysdig/releases/download/v0.0.1/extension.tar